#!bin/bash

if [[ -e $1 && -n $2 ]]
then
  if [[ -f $1 ]]
  then
  mkdir "$2"
  echo "$1 turinys: " 
  cat $1
    if [[ -x $1 ]]
    then
    cp $1 $2
    else
    printf "\n"
    read -p "Ar norite faila paversti vykdomuoju?(Y/n): " ats
      if [[  $ats == Y || $ats == y ]]
      then 
      chmod +x $1
      cp $1 $2
      ls -l
      echo "Viso gero"
      else
      echo "Viso gero"
      exit
      fi
    fi
  else
  echo "Netinkamas ivedimas"
  fi
else
echo "Netinkamas ivedimas"
fi
